import { CampaignStatsType, CampaignType } from './type';

/** Korzinka brendi (yashil) — uchinchi tomon reklama beruvchisi, BTS palitrasidan tashqarida */
const BRAND = { color: '#16A34A', initial: 'K' };

export const mockCampaigns: CampaignType[] = [
    {
        id: 'cmp-1',
        name: 'Yozgi chegirma',
        brandColor: BRAND.color,
        brandInitial: BRAND.initial,
        channels: ['parcel'],
        regions: ['Toshkent shahri', 'Samarqand'],
        goal: 1_000_000,
        delivered: 680_000,
        scans: 38_400,
        pace: 68,
        status: 'active',
        startDate: '2026-06-14',
        endDate: '2026-07-14',
        cpm: 112_000,
        creativeName: 'Kreativ A · Korzinka −20%',
    },
    {
        id: 'cmp-2',
        name: 'Bayram aksiyasi',
        brandColor: BRAND.color,
        brandInitial: BRAND.initial,
        channels: ['screen'],
        regions: ['Toshkent shahri'],
        goal: 300_000,
        delivered: 162_000,
        scans: 7_800,
        pace: 54,
        status: 'active',
        startDate: '2026-07-01',
        endDate: '2026-07-31',
        cpm: 98_000,
        creativeName: 'Bayram · ekran 16:9',
    },
    {
        id: 'cmp-3',
        name: 'Bahor kampaniyasi',
        brandColor: BRAND.color,
        brandInitial: BRAND.initial,
        channels: ['parcel'],
        regions: ['Toshkent shahri', "Farg'ona vodiysi"],
        goal: 500_000,
        delivered: 500_000,
        scans: 52_100,
        pace: 100,
        status: 'completed',
        startDate: '2026-05-01',
        endDate: '2026-05-31',
        cpm: 112_000,
        creativeName: 'Bahor · yorliq',
    },
    {
        id: 'cmp-4',
        name: 'Qishki savdo',
        brandColor: BRAND.color,
        brandInitial: BRAND.initial,
        channels: ['parcel', 'screen'],
        regions: ['Toshkent shahri', 'Samarqand', 'Buxoro'],
        goal: 800_000,
        delivered: 800_000,
        scans: 61_300,
        pace: 100,
        status: 'completed',
        startDate: '2026-01-10',
        endDate: '2026-02-10',
        cpm: 105_000,
        creativeName: 'Qishki savdo · yorliq',
    },
    {
        id: 'cmp-5',
        name: 'Maktabga tayyorgarlik',
        brandColor: BRAND.color,
        brandInitial: BRAND.initial,
        channels: ['parcel', 'screen'],
        regions: ['Toshkent shahri', 'Andijon', 'Namangan'],
        goal: 600_000,
        delivered: 0,
        scans: 0,
        pace: 0,
        status: 'moderation',
        startDate: '2026-08-01',
        endDate: '2026-08-31',
        cpm: 105_000,
        creativeName: 'Maktab · yorliq',
    },
    {
        id: 'cmp-6',
        name: 'Kuzgi yangilanish',
        brandColor: BRAND.color,
        brandInitial: BRAND.initial,
        channels: ['screen'],
        regions: ['Toshkent shahri'],
        goal: 400_000,
        delivered: 0,
        scans: 0,
        pace: 0,
        status: 'draft',
        startDate: '2026-09-01',
        endDate: '2026-09-30',
        cpm: 98_000,
        creativeName: '—',
    },
];

export const mockCampaignStats: CampaignStatsType = {
    activeCampaigns: 2,
    deliveringImpressions: 980_000,
    monthImpressions: 680_000,
    monthGoal: 1_000_000,
    scans: 46_200,
    scanRate: 6.8,
};
