import { CreativeType } from './type';

/** Korzinka brendi — DESIGN-SYSTEM §5 bo'yicha uchinchi tomon kreativi o'z rangida qoladi */
const BRAND_COLOR = '#16A34A';

export const mockCreatives: CreativeType[] = [
    {
        id: 'crt-1',
        name: 'Kreativ A · Korzinka −20%',
        kind: 'parcel',
        status: 'approved',
        badge: '−20%',
        brandColor: BRAND_COLOR,
        campaignName: 'Yozgi chegirma',
        impressions: 680_000,
        scans: 38_400,
        scanRate: 5.6,
        createdAt: '2026-06-10',
    },
    {
        id: 'crt-2',
        name: 'Bayram · ekran 16:9',
        kind: 'screen',
        status: 'approved',
        badge: 'BAYRAM',
        brandColor: '#0C3B2E',
        campaignName: 'Bayram aksiyasi',
        impressions: 162_000,
        scans: 7_800,
        scanRate: 4.8,
        createdAt: '2026-06-28',
    },
    {
        id: 'crt-3',
        name: 'Bahor · yorliq',
        kind: 'parcel',
        status: 'approved',
        badge: '−15%',
        brandColor: BRAND_COLOR,
        campaignName: 'Bahor kampaniyasi',
        impressions: 500_000,
        scans: 52_100,
        scanRate: 10.4,
        createdAt: '2026-04-22',
    },
    {
        id: 'crt-4',
        name: 'Maktab · yorliq',
        kind: 'parcel',
        status: 'moderation',
        badge: 'MAKTAB',
        brandColor: BRAND_COLOR,
        campaignName: 'Maktabga tayyorgarlik',
        impressions: 0,
        scans: 0,
        scanRate: 0,
        createdAt: '2026-07-24',
    },
    {
        id: 'crt-5',
        name: 'Qishki savdo · yorliq',
        kind: 'parcel',
        status: 'approved',
        badge: '−30%',
        brandColor: BRAND_COLOR,
        campaignName: 'Qishki savdo',
        impressions: 800_000,
        scans: 61_300,
        scanRate: 7.7,
        createdAt: '2026-01-05',
    },
    {
        id: 'crt-6',
        name: 'Yangi yil · yorliq',
        kind: 'parcel',
        status: 'rejected',
        badge: 'YANGI YIL',
        brandColor: '#A32B1C',
        impressions: 0,
        scans: 0,
        scanRate: 0,
        createdAt: '2026-07-19',
        rejectionReason:
            "QR kod yorliqning burchagida qolgan — skanerlashda o'qilmaydi. Markazga suring.",
    },
];
